$script = <<SCRIPT
cp /tmp/authorized_keys /home/ubuntu/.ssh/.
chown ubuntu:ubuntu /home/ubuntu/.ssh/authorized_keys
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "public_network", ip: "192.168.100.60"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end
  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/tmp/authorized_keys"
  config.vm.provision "shell", inline: $script
  # config.ssh.forward_agent = true
  # config.ssh.keys_only = false

  # Disables the vagrant generated key.
  # Uncomment if you only want access via user's key.
  # config.ssh.insert_key = false
end